# Importing Library

In [3]:
import numpy as np

# Array Atrributes

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

In [10]:
a.ndim

1

In [12]:
b = np.array([[1,2,3], [4,5,6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(b)

numpy.ndarray

In [18]:
b.shape

(2, 3)

In [19]:
b.ndim

2

In [20]:
c = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]]])
d = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [21]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [24]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('int32'), dtype('int32'), dtype('int32'))

In [25]:
c = np.array([[[1,2,3],
              [4,5,6],
              [7,8.0,9]]])
d = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [27]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('int32'), dtype('float64'), dtype('int32'))

In [28]:
a.size, b.size, c.size, d.size #determine how many elements are there an array

(3, 6, 9, 18)

In [29]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes #determine how many consumed by an array

(12, 24, 72, 72)

# Array Creation

In [30]:
array1 = np.array([1,2,3], dtype='int')

In [31]:
array1

array([1, 2, 3])

In [34]:
zerosVar = np.zeros((2,2), dtype='float')

In [35]:
zerosVar

array([[0., 0.],
       [0., 0.]])

In [36]:
zerosVar = np.zeros((3,3), dtype ='int')

In [37]:
zerosVar

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
onesVal = np.ones((3,3), dtype ='int')

In [39]:
onesVal

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
fullVar = np.full((2,3), 5)

In [43]:
fullVar

array([[5, 5, 5],
       [5, 5, 5]])

In [44]:
identity = np.identity(3, dtype = 'int')

In [45]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
eyeVar = np.eye(3,3)

In [47]:
eyeVar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
eyeVar2 = np.eye(3,3,1) # 1 goes 1 side right

In [49]:
eyeVar2

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [50]:
eyeVar3 = np.eye(3,3,2) #1 goes 2 sides right

In [51]:
eyeVar3

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
eyeVar4 = np.eye(3,3,-1) #1 goes 1 side left

In [53]:
eyeVar4

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [54]:
arangeVar = np.arange(1, 10, 2) #range 1 to <10 and difference between 2 with them

In [55]:
arangeVar

array([1, 3, 5, 7, 9])

In [56]:
arangeVar2 = np.arange(1, 10, 3) #range 1 to <10 and difference between 3 with them

In [57]:
arangeVar2

array([1, 4, 7])

In [58]:
linspaceVar = np.linspace(1, 5, 10)

In [59]:
linspaceVar

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [60]:
linspaceVar2 = np.linspace(1, 5, 50)

In [61]:
linspaceVar2

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [62]:
linspaceVar3 = np.linspace(1, 100, 50, dtype = 'int')

In [63]:
linspaceVar3

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [64]:
linspaceVar3.size

50

In [65]:
emptyVar = np.empty((1,5))

In [66]:
emptyVar

array([[2.12199579e-314, 8.06358401e-312, 1.83792420e-321,
        8.06358401e-312, 5.63234836e-322]])

In [68]:
for i in range(5):
    emptyVar[:,i] = i
emptyVar

array([[0., 1., 2., 3., 4.]])