# Importing Library

In [3]:
import numpy as np

# Array Atrributes

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

In [10]:
a.ndim

1

In [12]:
b = np.array([[1,2,3], [4,5,6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(b)

numpy.ndarray

In [18]:
b.shape

(2, 3)

In [19]:
b.ndim

2

In [20]:
c = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]]])
d = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [21]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [24]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('int32'), dtype('int32'), dtype('int32'))

In [25]:
c = np.array([[[1,2,3],
              [4,5,6],
              [7,8.0,9]]])
d = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [27]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('int32'), dtype('float64'), dtype('int32'))

In [28]:
a.size, b.size, c.size, d.size #determine how many elements are there an array

(3, 6, 9, 18)

In [29]:
a.nbytes, b.nbytes, c.nbytes, d.nbytes #determine how many consumed by an array

(12, 24, 72, 72)