# Array Indexing and Slicing

# Indexing

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])

In [3]:
print(arr1)

[1 2 3 4 5]


In [4]:
arr1[0]

1

In [5]:
arr1[2]

3

In [6]:
arr1[-1]

5

In [7]:
arr1[-3]

3

In [8]:
arr2 = np.random.randint(1, 10, size = (3, 3))

In [9]:
print(arr2)

[[7 3 1]
 [3 6 1]
 [1 8 8]]


In [10]:
arr2[0][0]

7

In [11]:
arr2[1][1]

6

In [12]:
arr2[1,1]

6

In [13]:
arr3 = np.random.randint(1, 10, size = (2, 3, 3))

In [14]:
print(arr3)

[[[4 3 3]
  [3 4 5]
  [8 5 9]]

 [[8 3 1]
  [7 6 2]
  [3 9 5]]]


In [15]:
arr3[0][1][1]

4

In [16]:
arr3[1, 1, 1]

6

In [17]:
arr3[0, 2, 1]

5

In [21]:
arr3[1, 2, 2]

5

# Slicing

In [22]:
print(arr1)

[1 2 3 4 5]


In [23]:
print(arr1[0: 3])

[1 2 3]


In [24]:
print(arr1[2:])

[3 4 5]


In [25]:
arr2

array([[7, 3, 1],
       [3, 6, 1],
       [1, 8, 8]])

In [26]:
arr2[0: 2, 0: 2]

array([[7, 3],
       [3, 6]])

In [28]:
arr2[0: 2, 0: 3]

array([[7, 3, 1],
       [3, 6, 1]])

In [29]:
arr2[0: 3, 0: 2]

array([[7, 3],
       [3, 6],
       [1, 8]])

In [30]:
arr2[1: , 1: ]

array([[6, 1],
       [8, 8]])