# reshape()

In [3]:
import numpy as np
a = np.array([[1, 2, 3],
             [4, 5, 6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [7]:
a_reshaped = np.reshape(a, (3, 2))

In [8]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a_reshaped.shape

(3, 2)

In [10]:
a_reshaped2 = np.reshape(a, (3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

# resize()

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a_resized = np.resize(a, (3, 3))

In [17]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [18]:
a_resized = np.resize(a, (4, 3))

In [19]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
a_resized2 = np.resize(a, (3, 2))

In [21]:
a_resized2

array([[1, 2],
       [3, 4],
       [5, 6]])