# ravel()

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1, 10, (2, 3)) #return a view of the array

In [4]:
a

array([[9, 5, 2],
       [8, 5, 9]])

In [5]:
a_raveled = np.ravel(a)

In [6]:
a_raveled

array([9, 5, 2, 8, 5, 9])

In [11]:
a_raveled.shape

(6,)

In [12]:
a_raveled[0] = 0

In [13]:
a_raveled

array([0, 5, 2, 8, 5, 9])

In [14]:
a

array([[0, 5, 2],
       [8, 5, 9]])

# flatten

In [15]:
a

array([[0, 5, 2],
       [8, 5, 9]])

In [16]:
a_flattened = a.flatten() #Return a copy of the array, always allocates a new memory

In [17]:
a_flattened

array([0, 5, 2, 8, 5, 9])

In [18]:
a_flattened

array([0, 5, 2, 8, 5, 9])

In [19]:
a_flattened[0] = 100

In [20]:
a_flattened

array([100,   5,   2,   8,   5,   9])

In [21]:
a

array([[0, 5, 2],
       [8, 5, 9]])

# defining an array shape

In [22]:
a

array([[0, 5, 2],
       [8, 5, 9]])

In [23]:
a.shape = (3, 2)

In [24]:
a

array([[0, 5],
       [2, 8],
       [5, 9]])

In [25]:
a.shape = (5, 2)

ValueError: cannot reshape array of size 6 into shape (5,2)