# Stacking

# Horizontal Stacking

In [15]:
import numpy as np

In [16]:
a = np.arange(1, 10). reshape(3, 3)

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b = 2*a

In [19]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
np.hstack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [21]:
np.column_stack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [22]:
 np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

# Vertical Stacking

In [23]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
np.row_stack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
np.concatenate((a, b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Depth Stack

In [26]:
np.dstack((a, b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])